leading_systems_contao_cache:
  pools:
    - id: merconis.search
      namespace_prefix: 'merconis.search.cache.'
      maintenance_job: true
      label:
        en: 'Merconis search cache'
        de: 'Merconis Such-Cache'


