services:

  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  merconis.routing.scope:
    class: LeadingSystems\MerconisBundle\Services\Scope
    public: true

  merconis.helpers.general:
    class: LeadingSystems\MerconisBundle\Helpers\GeneralHelper
    arguments:
      - '@merconis.helpers.ip_checker'
    public: true

  merconis.helpers.ip_checker:
    class: LeadingSystems\MerconisBundle\Helpers\IpChecker
    public: true

  LeadingSystems\MerconisBundle\EventSubscriber\LsjsInsertionSubscriber:
    arguments:
      - '@contao.framework'
      - '@contao.routing.scope_matcher'
      - '@contao.security.token_checker'
      - '%contao.web_dir%'
      - '%kernel.project_dir%'
    tags:
      - { name: 'kernel.event_subscriber' }

  LeadingSystems\MerconisBundle\EventListener\GetPageLayoutListener:
    tags:
      - { name: contao.hook, hook: getPageLayout, method: switchTemplateInDetailsViewIfNecessary }
      - { name: contao.hook, hook: getPageLayout, method: getLayoutSettingsForGlobalUse }

  LeadingSystems\MerconisBundle\EventListener\GeneratePageListener:
    tags:
      - { name: contao.hook, hook: generatePage }

  LeadingSystems\MerconisBundle\EventListener\LoadLanguageFileListener:
    tags:
      - { name: contao.hook, hook: loadLanguageFile }

  LeadingSystems\MerconisBundle\EventListener\OutputBackendTemplateListener:
    tags:
      - { name: contao.hook, hook: outputBackendTemplate }

  LeadingSystems\MerconisBundle\EventListener\LoadFormFieldListener:
    tags:
      - { name: contao.hook, hook: loadFormField }

  LeadingSystems\MerconisBundle\EventListener\GetContentElementListener:
    tags:
      - { name: contao.hook, hook: getContentElement }

  LeadingSystems\MerconisBundle\EventListener\GetArticleListener:
    tags:
      - { name: contao.hook, hook: getArticle }

  LeadingSystems\MerconisBundle\EventListener\LoadDataContainerListener:
    tags:
      - { name: contao.hook, hook: loadDataContainer }

  LeadingSystems\MerconisBundle\EventListener\ModifyFrontendPageListener:
    tags:
      - { name: contao.hook, hook: modifyFrontendPage }

  LeadingSystems\MerconisBundle\EventListener\GetUserNavigationListener:
    tags:
      - { name: contao.hook, hook: getUserNavigation}

  LeadingSystems\MerconisBundle\EventListener\GetSystemMessagesListener:
    tags:
      - { name: contao.hook, hook: getSystemMessages }

  LeadingSystems\MerconisBundle\EventListener\InitializeSystemListener:
    tags:
      - { name: contao.hook, hook: initializeSystem }

  LeadingSystems\MerconisBundle\EventListener\OutputFrontendTemplateListener:
    tags:
      - { name: contao.hook, hook: outputFrontendTemplate }

  LeadingSystems\MerconisBundle\EventListener\ProcessFormDataListener:
    tags:
      - { name: contao.hook, hook: processFormData }

  LeadingSystems\MerconisBundle\EventListener\ExecutePreActionsListener:
    tags:
      - { name: contao.hook, hook: executePreActions }

  LeadingSystems\MerconisBundle\EventListener\ExecutePostActionsListener:
    tags:
      - { name: contao.hook, hook: executePostActions }

  LeadingSystems\MerconisBundle\EventListener\AddCustomRegexpListener:
    tags:
      - { name: contao.hook, hook: addCustomRegexp }

  LeadingSystems\MerconisBundle\EventListener\RequestListener:
    arguments:
      - '@contao.framework'
      - '@contao.routing.scope_matcher'
      - '@merconis.helpers.general'
    tags:
      - { name: kernel.event_listener, priority: 15 }

  merconis.eventlistener.loginlistener:
    class: LeadingSystems\MerconisBundle\EventListener\LoginListener
    tags:
      - { name: kernel.event_listener, event: security.interactive_login }

  merconis.eventlistener.sitemaplistener:
    class: LeadingSystems\MerconisBundle\EventListener\SitemapListener
    tags:
      - { name: kernel.event_listener, event: contao.sitemap }

  merconis.controller.backend.product_search:
    class: LeadingSystems\MerconisBundle\Controller\ProductSearchController
    public: true
    arguments:
      - "@contao.framework"

  merconis.controller.backend.pick_value:
    class: LeadingSystems\MerconisBundle\Controller\ValuePickerController
    public: true
    arguments:
      - "@contao.framework"

  merconis.controller.backend.show_mail:
    class: LeadingSystems\MerconisBundle\Controller\ShowMailController
    public: true
    arguments:
      - "@database_connection"
      - "@twig"

  merconis.listener.data_container.layout_options:
    class: Contao\CoreBundle\EventListener\DataContainer\LayoutOptionsListener
    arguments:
      - '@database_connection'
    tags:
      - { name: contao.callback, table: tl_page, target: fields.lsShopLayoutForDetailsView.options }

  merconis.cron.hourly:
    class: LeadingSystems\MerconisBundle\Cronjob\Hourly
    tags:
      - { name: contao.cronjob, interval: hourly }

  merconis.cron.daily:
    class: LeadingSystems\MerconisBundle\Cronjob\Daily
    tags:
      - { name: contao.cronjob, interval: daily }

  LeadingSystems\MerconisBundle\InsertTag\AsInsertTag\:
    resource: '../../InsertTag/AsInsertTag'

  LeadingSystems\MerconisBundle\InsertTag\AsBlockInsertTag\:
    resource: '../../InsertTag/AsBlockInsertTag'
