services:

  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  merconis.routing.scope:
    class: LeadingSystems\MerconisBundle\Services\Scope
    public: true

  merconis.helpers.general:
    class: LeadingSystems\MerconisBundle\Helpers\GeneralHelper
    public: true
    
  LeadingSystems\MerconisBundle\EventSubscriber\LsjsInsertionSubscriber:
    arguments:
      - '@contao.framework'
      - '@contao.routing.scope_matcher'
      - '@contao.security.token_checker'
      - '%contao.web_dir%'
      - '%kernel.project_dir%'
    tags:
      - { name: 'kernel.event_subscriber' }

  LeadingSystems\MerconisBundle\EventListener\GetPageLayoutListener:
    tags:
      - { name: contao.hook, hook: getPageLayout, method: switchTemplateInDetailsViewIfNecessary }
      - { name: contao.hook, hook: getPageLayout, method: getLayoutSettingsForGlobalUse }

  LeadingSystems\MerconisBundle\EventListener\RequestListener:
    arguments:
      - '@contao.framework'
      - '@contao.routing.scope_matcher'
      - '@merconis.helpers.general'
    tags:
      - { name: kernel.event_listener, priority: 15 }

  merconis.eventlistener.loginlistener:
    class: LeadingSystems\MerconisBundle\EventListener\LoginListener
    tags:
      - { name: kernel.event_listener, event: security.interactive_login }

  merconis.eventlistener.sitemaplistener:
    class: LeadingSystems\MerconisBundle\EventListener\SitemapListener
    tags:
      - { name: kernel.event_listener, event: contao.sitemap }

  merconis.controller.backend.product_search:
    class: LeadingSystems\MerconisBundle\Controller\ProductSearchController
    public: true
    arguments:
      - "@contao.framework"

  merconis.controller.backend.pick_value:
    class: LeadingSystems\MerconisBundle\Controller\ValuePickerController
    public: true
    arguments:
      - "@contao.framework"

  merconis.controller.backend.show_mail:
    class: LeadingSystems\MerconisBundle\Controller\ShowMailController
    public: true
    arguments:
      - "@database_connection"
      - "@twig"

  merconis.listener.data_container.layout_options:
    class: Contao\CoreBundle\EventListener\DataContainer\LayoutOptionsListener
    arguments:
      - '@database_connection'
    tags:
      - { name: contao.callback, table: tl_page, target: fields.lsShopLayoutForDetailsView.options }

  merconis.cron.hourly:
    class: LeadingSystems\MerconisBundle\Cronjob\Hourly
    tags:
      - { name: contao.cronjob, interval: hourly }

  merconis.cron.daily:
    class: LeadingSystems\MerconisBundle\Cronjob\Daily
    tags:
      - { name: contao.cronjob, interval: daily }