services:
  merconis.controller.backend.product_search:
    class: LeadingSystems\MerconisBundle\Controller\ProductSearchController
    public: true
    arguments:
      - "@contao.framework"

  merconis.controller.backend.pick_value:
    class: LeadingSystems\MerconisBundle\Controller\ValuePickerController
    public: true
    arguments:
      - "@contao.framework"

  merconis.controller.backend.show_mail:
    class: LeadingSystems\MerconisBundle\Controller\ShowMailController
    public: true
    arguments:
      - "@database_connection"
      - "@twig"

  merconis.listener.layout_options:
    class: LeadingSystems\MerconisBundle\EventListener\LayoutOptionsListener
    arguments:
      - '@database_connection'
    tags:
      - { name: kernel.reset, method: reset }