services:

  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  merconis.routing.scope:
    class: LeadingSystems\MerconisBundle\Services\Scope

  merconis.controller.backend.product_search:
    class: LeadingSystems\MerconisBundle\Controller\ProductSearchController
    public: true
    arguments:
      - "@contao.framework"

  merconis.controller.backend.pick_value:
    class: LeadingSystems\MerconisBundle\Controller\ValuePickerController
    public: true
    arguments:
      - "@contao.framework"

  merconis.controller.backend.show_mail:
    class: LeadingSystems\MerconisBundle\Controller\ShowMailController
    public: true
    arguments:
      - "@database_connection"
      - "@twig"

  merconis.listener.data_container.layout_options:
    class: Contao\CoreBundle\EventListener\DataContainer\LayoutOptionsListener
    arguments:
      - '@database_connection'
    tags:
      - { name: contao.callback, table: tl_page, target: fields.lsShopLayoutForDetailsView.options }