services:

  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  LeadingSystems\MerconisBundle\EventSubscriber\LsjsInsertionSubscriber:
    arguments:
      - '@contao.framework'
      - '@contao.routing.scope_matcher'
      - '%contao.web_dir%'
      - '%kernel.project_dir%'
    tags:
      - { name: 'kernel.event_subscriber' }


  LeadingSystems\MerconisBundle\EventListener\GetPageLayoutListener:
    tags:
      - { name: contao.hook, hook: getPageLayout, method: getLayoutSettingsForGlobalUse }

  merconis.eventlistener.loginlistener:
    class: LeadingSystems\MerconisBundle\EventListener\LoginListener
    tags:
      - { name: kernel.event_listener, event: security.interactive_login }

  merconis.eventlistener.sitemaplistener:
    class: LeadingSystems\MerconisBundle\EventListener\SitemapListener
    tags:
      - { name: kernel.event_listener, event: contao.sitemap }

  merconis.controller.backend.product_search:
    class: LeadingSystems\MerconisBundle\Controller\ProductSearchController
    public: true
    arguments:
      - "@contao.framework"

  merconis.controller.backend.pick_value:
    class: LeadingSystems\MerconisBundle\Controller\ValuePickerController
    public: true
    arguments:
      - "@contao.framework"

  merconis.controller.backend.show_mail:
    class: LeadingSystems\MerconisBundle\Controller\ShowMailController
    public: true
    arguments:
      - "@database_connection"
      - "@twig"

  merconis.listener.data_container.layout_options:
    class: Contao\CoreBundle\EventListener\DataContainer\LayoutOptionsListener
    arguments:
      - '@database_connection'
    tags:
      - { name: contao.callback, table: tl_page, target: fields.lsShopLayoutForDetailsView.options }