services:

  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  merconis.routing.scope:
    class: LeadingSystems\MerconisBundle\Services\Scope
    public: true

  merconis.helpers.general:
    class: LeadingSystems\MerconisBundle\Helpers\GeneralHelper
    arguments:
      - '@merconis.helpers.ip_checker'
    public: true

  merconis.helpers.ip_checker:
    class: LeadingSystems\MerconisBundle\Helpers\IpChecker
    public: true

  LeadingSystems\MerconisBundle\EventSubscriber\LsjsInsertionSubscriber:
    arguments:
      - '@contao.framework'
      - '@contao.routing.scope_matcher'
      - '@contao.security.token_checker'
      - '%contao.web_dir%'
      - '%kernel.project_dir%'
    tags:
      - { name: 'kernel.event_subscriber' }

  LeadingSystems\MerconisBundle\EventListener\GetPageLayoutListener:
    tags:
      - { name: contao.hook, hook: getPageLayout, method: switchTemplateInDetailsViewIfNecessary }
      - { name: contao.hook, hook: getPageLayout, method: getLayoutSettingsForGlobalUse }

  LeadingSystems\MerconisBundle\EventListener\RequestListener:
    arguments:
      - '@contao.framework'
      - '@contao.routing.scope_matcher'
      - '@merconis.helpers.general'
    tags:
      - { name: kernel.event_listener, priority: 15 }

  merconis.eventlistener.loginlistener:
    class: LeadingSystems\MerconisBundle\EventListener\LoginListener
    tags:
      - { name: kernel.event_listener, event: security.interactive_login }

  merconis.eventlistener.sitemaplistener:
    class: LeadingSystems\MerconisBundle\EventListener\SitemapListener
    tags:
      - { name: kernel.event_listener, event: contao.sitemap }

  merconis.controller.backend.product_search:
    class: LeadingSystems\MerconisBundle\Controller\ProductSearchController
    public: true
    arguments:
      - "@contao.framework"

  merconis.controller.backend.pick_value:
    class: LeadingSystems\MerconisBundle\Controller\ValuePickerController
    public: true
    arguments:
      - "@contao.framework"

  merconis.controller.backend.show_mail:
    class: LeadingSystems\MerconisBundle\Controller\ShowMailController
    public: true
    arguments:
      - "@database_connection"
      - "@twig"

  merconis.listener.data_container.layout_options:
    class: Contao\CoreBundle\EventListener\DataContainer\LayoutOptionsListener
    arguments:
      - '@database_connection'
    tags:
      - { name: contao.callback, table: tl_page, target: fields.lsShopLayoutForDetailsView.options }

  merconis.cron.hourly:
    class: LeadingSystems\MerconisBundle\Cronjob\Hourly
    tags:
      - { name: contao.cronjob, interval: hourly }

  merconis.cron.daily:
    class: LeadingSystems\MerconisBundle\Cronjob\Daily
    tags:
      - { name: contao.cronjob, interval: daily }

  LeadingSystems\MerconisBundle\InsertTag\AsInsertTag\:
    resource: '../../InsertTag/AsInsertTag'

  LeadingSystems\MerconisBundle\InsertTag\AsBlockInsertTag\:
    resource: '../../InsertTag/AsBlockInsertTag'


  Merconis\Core\ls_shop_generalHelper:
    tags:
      - { name: contao.hook, hook: generatePage, method: ls_shop_provideInfosForJS}
      - { name: contao.hook, hook: loadLanguageFile, method: ls_shop_loadThemeLanguageFiles }
      - { name: contao.hook, hook: outputBackendTemplate, method: merconis_getBackendLsjs }
      - { name: contao.hook, hook: loadFormField, method: handleConditionalFormFields }
      - { name: contao.hook, hook: getContentElement, method: conditionalCTEOutput }
      - { name: contao.hook, hook: getArticle, method: conditionalArticleOutput }
      - { name: contao.hook, hook: outputFrontendTemplate, method: callback_outputFrontendTemplate }
      - { name: contao.hook, hook: loadDataContainer, method: removeFieldsForEditAll }
      - { name: contao.hook, hook: modifyFrontendPage, method: storeConfiguratorDataToSession }
      - { name: contao.hook, hook: modifyFrontendPage, method: storeCustomizerDataToSession }
      - { name: contao.hook, hook: getUserNavigation, method: manipulateBackendNavigation }
      - { name: contao.hook, hook: getSystemMessages, method: getMerconisSystemMessages }

  Merconis\Core\ls_shop_cartHelper:
    tags:
      - { name: contao.hook, hook: initializeSystem, method: initializeEmptyCart }

  LeadingSystems\MerconisBundle\Services\FilterController:
    tags:
      - { name: contao.hook, hook: outputFrontendTemplate, method: generateAndInsertFilterForms }

  LeadingSystems\MerconisBundle\Services\CheckoutData:
    tags:
      - { name: contao.hook, hook: processFormData, method: ls_shop_processFormData }
      - { name: contao.hook, hook: loadFormField, method: ls_shop_loadFormField }

  Merconis\Core\ls_shop_ajaxController:
    tags:
      - { name: contao.hook, hook: executePreActions, method: executePreActions }
      - { name: contao.hook, hook: executePostActions, method: executePostActions }

  Merconis\Core\ls_shop_custom_regexp:
    tags:
      - { name: contao.hook, hook: addCustomRegexp, method: customRegexp }

  Merconis\Core\ls_shop_custom_regexp_fe:
    tags:
      - { name: contao.hook, hook: addCustomRegexp, method: customRegexp }

