<?php

	/*
	 * Fields
	 */
	$GLOBALS['TL_LANG']['tl_layout']['ls_shop_filterMode'] = ['Product filter', 'Determines whether and with which filter technology the product list can be filtered.'];
	$GLOBALS['TL_LANG']['tl_layout']['ls_shop_filterMode_options'] = [
		'' => ['Disabled', 'No product filter is active. Product lists are displayed without filter technology.'],
		'classic' => ['Classic filter (default)', 'Activates the classic filter technology with the full product filter feature set.'],
		'fast' => ['Fast filter technology (limited)', 'Activates the fast filter technology with limited functionality. Only attribute filters with OR logic and manufacturer filters are available.']
	];
	$GLOBALS['TL_LANG']['tl_layout']['ls_shop_fastFilterAutoSubmit'] = ['Apply filter automatically when changed', 'Submits the fast filter form automatically when a checkbox or radio selection changes.'];
	$GLOBALS['TL_LANG']['tl_layout']['ls_shop_fastFilterHideZeroMatches'] = ['Hide filter options without matches', 'Fully hides options with 0 estimated matches in the fast filter.'];
	$GLOBALS['TL_LANG']['tl_layout']['ls_shop_fastFilterResetMode'] = ['Filter reset logic', 'Defines when active fast filters are reset automatically during category changes.'];
	$GLOBALS['TL_LANG']['tl_layout']['ls_shop_fastFilterResetMode_options'] = [
		'never' => 'Never reset automatically',
		'always' => 'Reset automatically on every category change',
		'branch' => 'Reset only when changing outside the page branch',
	];
	$GLOBALS['TL_LANG']['tl_layout']['ls_shop_useFilterInStandardProductlist'] = array('Use filter in standard product overview', 'Select this option if you want to use the product filter in product lists generated by the frontend module "product overview" (e.g. the typical category view)');
	$GLOBALS['TL_LANG']['tl_layout']['ls_shop_useFilterMatchEstimates'] = array('Determine estimated number of matches');
    $GLOBALS['TL_LANG']['tl_layout']['ls_shop_numFilterFieldsInSummary'] = array('Number of filter fields to display in summary');
	$GLOBALS['TL_LANG']['tl_layout']['ls_shop_matchEstimatesMaxNumProducts'] = array('Product limit for estimated matches', 'Depending on the performance of your server it might be useful to limit the number of products in your product list for which the estimated number of matches will be determined.');
	$GLOBALS['TL_LANG']['tl_layout']['ls_shop_matchEstimatesMaxFilterValues'] = array('Filter value limit for estimated matches', 'Depending on the performance of your server it might be useful to limit the number of filter values in your filter form for which the estimated number of matches will be determined.');
	$GLOBALS['TL_LANG']['tl_layout']['ls_shop_useFilterInProductDetails'] = array('Use filter in product details', 'Select this option if you want to use the filter in the product details which enables variant filtering.');
	$GLOBALS['TL_LANG']['tl_layout']['ls_shop_hideFilterFormInProductDetails'] = array('Hide filter form in product details');

	/*
	 * Legends
	 */
	$GLOBALS['TL_LANG']['tl_layout']['lsShopFilter_legend']   = 'MERCONIS: Filter settings';
	$GLOBALS['TL_LANG']['tl_layout']['lsShopJsComponents_legend']   = 'MERCONIS: Javascript plug-Ins';
